#! /usr/bin/env python

import os, sys, subprocess, traceback

if str==bytes:
    from urlparse import parse_qs, parse_qsl
    from urllib import urlencode
else:
    from urllib.parse import parse_qs, parse_qsl
    from urllib.parse import urlencode
    sys.stdout=sys.stdout.buffer
    sys.stdin=sys.stdin.buffer

try:
    if os.environ["REQUEST_METHOD"]!="POST":
        sys.stdout.write(b"Status: 405 Method Not Allowed\n\nOnly POST method is allowed\n")
        sys.exit(0)

except Exception:
    sys.stdout.write(b"Status: 500 Internal Server Error\n\n"+traceback.format_exc().encode("utf8")+b"\n")
    sys.exit(0)

cryptaurInstallationDirectory="/opt/cryptaur"
if not os.path.isdir(cryptaurInstallationDirectory):
    cryptaurInstallationDirectory=os.path.join(os.pardir, os.pardir)

coinname=os.path.basename(os.path.abspath(os.path.dirname(sys.argv[0])))
executable=os.path.join(cryptaurInstallationDirectory, "bin", "getinfo-{0}.py".format(coinname))

if os.access(executable, os.X_OK):
    sys.stdout.write(b"Status: 200 OK\nContent-Type: application/json\n\n")
    sys.stdout.flush()
    subprocess.call([executable])
else:
    sys.stdout.write(b"Status: 404 Not Found\n\n")
